package hu.neuron.imaginer.exception;

public enum ErrorType {
	NO_USER_WITH_ID,
	NO_USER_WITH_USERNAME,
	NO_USER_WITH_EMAIL,
	REGISTRATION_ERROR,
	TOKEN_CREATION_ERROR,
	TOKEN_NOT_FOUND,
	AUTHENTICATION_ERROR,
	FAILED_TO_STORE_IMAGE,
	FAILED_TO_STORE_GALLERY,
	FAILED_TO_GET_GALLERIES,
	FAILED_TO_GET_IMAGES,
	FAILED_TO_GET_IMAGE,
	FAILED_TO_GET_GALLERY,
	NO_SUCH_GALLERY,
	NO_SUCH_IMAGE,
	GALLERY_ALREADY_EXISTS, 
	IMAGE_ALREADY_EXISTS
}
